Import('*')

SimObject('MAA.py', sim_objects=['MAA'])

Source('SPD.cc')
Source('IF.cc')
Source('IndirectAccess.cc')
Source('StreamAccess.cc')
Source('Invalidator.cc')
Source('ALU.cc')
Source('MAA.cc')

DebugFlag('MAA')
DebugFlag('MAACpuPort')
DebugFlag('MAACachePort')
DebugFlag('MAAMemPort')
DebugFlag('MAAController')
DebugFlag('MAAIndirect')
DebugFlag('MAAStream')
DebugFlag('MAAInvalidator')
DebugFlag('MAAALU')

# MAA Tags is so outrageously verbose, printing the MAA's entire tag
# array on each timing access, that you should probably have to ask for
# it explicitly even above and beyond MAAAll.
CompoundFlag('MAAAll', ['MAA', 'MAACpuPort', 'MAACachePort', 'MAAMemPort', 'MAAController', 'MAAIndirect', 'MAAStream', 'MAAInvalidator'])
